version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn start:dev
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
